### ISSUE TITLE
following usage guide results in error 

### ISSUE THREAD

**Issue by dudenamedjune** [JSextonn/wardle#1]
steps to reproduce 

```bash
./wardle help
```

```bash
output: permission denied
```

**Comment by jusexton** [comment]
Mind posting the output of `rustup --version`?

And I am assuming you executed the following commands before attempting to run the app?
`cargo build`
`cd /target/debug`

**Comment by dudenamedjune** [comment]
<img width="1998" alt="Screen Shot 2022-02-24 at 1 29 16 AM" src="https://user-images.githubusercontent.com/8673104/155478203-0bb41ca5-8f84-46c5-9fff-1dd3bec16924.png">
here is a slew of commands some of them are me just being an idiot

**Comment by dudenamedjune** [comment]
also tried to run in one directory up

**Comment by jusexton** [comment]
Doesnt look like you have rustup installed correctly which may be an issue but I also dont ever see you ever successfully executing the app while in the debug directory. You navigate there but never run the commands from that directory.

**Comment by dudenamedjune** [comment]
sweet, thanks mate opened this in case anyone else has similar issues 
https://github.com/JSextonn/wardle/pull/2
